pycones/newsletter/urls.py
from django.conf.urls.defaults import url, patterns

urlpatterns = patterns("pycones.newsletter.views",
    url(r"^subscribe/$", "subscribe_newsletter", name="subscribe_newsletter"),
    url(r"^unsubscribe/$", "unsubscribe_newsletter", name="unsubscribe_newsletter"),
    url(r"^latest/$", "latest_newsletter", name="latest_newsletter"),
    url(r"^article/(?P<slug>[\w\-\d]+)/$","article", name="article"),
    url(r"^(?P<uuid>[\w\-\d]+)/$", "newsletter", name="newsletter"),
)

pycones/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from django.views.generic.simple import direct_to_template
#Changes 1.5
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from rest_framework.routers import DefaultRouter
from pycones.call4papers.api import TalkViewSet, SpeakerViewSet
from pycones.sponsors.api import SponsorViewSet

api_router = DefaultRouter()
api_router.register('talks', TalkViewSet)
api_router.register('speakers', SpeakerViewSet)
api_router.register('sponsors', SponsorViewSet)


urlpatterns = patterns("",
    url(r"^", include('pycones.web.urls')),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^api/v1/", include(api_router.urls)),
    url(r"^newsletter/", include("pycones.newsletter.urls", namespace="newsletter")),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

def mediafiles_urlpatterns():
    """
    Method for serve media files with runserver.
    """

    _media_url = settings.MEDIA_URL
    if _media_url.startswith('/'):
        _media_url = _media_url[1:]

    from django.views.static import serve
    return patterns('',
        (r'^%s(?P<path>.*)$' % _media_url, serve,
            {'document_root': settings.MEDIA_ROOT})
    )


# This only works on development mode
urlpatterns += staticfiles_urlpatterns()
urlpatterns += mediafiles_urlpatterns()

pycones/call4papers/models.py
# -*- coding: utf-8 -*-

from django.db import models

class Speaker(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    twitter = models.CharField(max_length=100,
                    blank=True, null=True)
    web = models.CharField(max_length=100,
                    blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = u'ponente'
        ordering = ['name',]

    def __unicode__(self):
        return self.name

TALK_LEVELS = (
    ('basic', u'Básico'),
    ('advanced', u'Avanzado'),
    ('scientific', u'Científico'),
)
SC_DAY = (('s', u'Sábado'), ('d', u'Domingo'))
SC_TRACK = (('b', u'Básico'), ('a', u'Avanzado'), ('c', u'Científico'))
SC_HOUR = (
    ('9', u'9'),
    ('10', u'10'),
    ('11', u'11:30'),
    ('12', u'12:30'),
    ('15', u'15'),
    ('16', u'16'),
    ('17', u'17:30'),
    ('18', u'18:30'),
)

class Talk(models.Model):
    title = models.CharField(max_length=200)
    level = models.CharField(max_length=100, choices=TALK_LEVELS,
                        blank=True, null=True)
    speakers = models.ManyToManyField(Speaker, related_name='talks')
    abstract = models.TextField(blank=True, null=True)
    selected = models.BooleanField(default=False)
    confirmed = models.BooleanField(default=False)
    sc_hour = models.CharField(max_length=2,
                        blank=True, null=True,
                        choices=SC_HOUR)
    sc_track = models.CharField(max_length=1,
                        blank=True, null=True,
                        choices=SC_TRACK)
    sc_day = models.CharField(max_length=1,
                        blank=True, null=True,
                        choices=SC_DAY)
    slot = models.CharField(max_length=10,
                        blank=True, null=True,
                        unique=True)

    def _slot(self):
        return u'{}{}{}'.format(self.sc_track, self.sc_day, self.sc_hour)

    class Meta:
        verbose_name = u'charla'
        unique_together = ['sc_track', 'sc_day', 'sc_hour']

    def __unicode__(self):
        return self.title

    def save(self):
        if self.sc_day != None and self.sc_track != None and self.sc_hour != None:
            self.slot = self._slot()
        super(Talk, self).save()

pycones/sponsors/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User


SPONSOR_LEVELS = (
    ('diamond', u'DIAMANTE'),
    ('platinum', u'PLATINO'),
    ('gold', u'ORO'),
    ('silver', u'PLATA'),
    ('bronce', u'BRONCE'),
)

class Sponsor(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=255)
    level = models.CharField(max_length=100, choices=SPONSOR_LEVELS)
    image = models.ImageField(upload_to='.')

    class Meta:
        verbose_name = u'patrocinador'
        verbose_name_plural = u'patrocinadores'

    def __unicode__(self):
        return self.name


STATUS_LEVELS = (
    ('reject', u'Rechazo'),
    ('objection', u'Objeción'),
    ('waiting', u'A la espera'),
    ('accepted', u'Aceptado'),
)

ACCEPTED_LEVEL = (('none', u'NONE'),) + SPONSOR_LEVELS

INVOICE_STATUS = (
    ('none', u'None'),
    ('sent', u'Enviada'),
    ('aceptada', u'Aceptada'),
    ('recibida', u'Recibida'),
)

class Prospect(models.Model):
    company = models.CharField(max_length=100)
    web = models.CharField(max_length=255, blank=True, null=True)
    contact_name = models.CharField(max_length=100, blank=True, null=True)
    email =  models.CharField(max_length=100)
    previous_interest = models.BooleanField(default=False)
    already_contacted = models.BooleanField(default=False)
    status = models.CharField(max_length=100, choices=STATUS_LEVELS,
                        null=True, blank=True)
    user_in_charge = models.ForeignKey(User, blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    accepted_level = models.CharField(max_length=100, choices=ACCEPTED_LEVEL, default=ACCEPTED_LEVEL[0])
    invoice_status = models.CharField(max_length=100, choices=INVOICE_STATUS, default=INVOICE_STATUS[0])

    class Meta:
        verbose_name = u'candidato'
        verbose_name_plural = u'candidatos'

    def __unicode__(self):
        return self.company

pycones/web/templates/web/accommodation.html
{% load static from staticfiles %}
{% load i18n %}

<article class="accommodation" id="alojamiento">
    <div class="accommodation-inside">
        <h2 class="white title">{% trans 'Alojamiento' %}</h2>
        {% blocktrans %}
        <p>El campus sur de la UPM está algo apartado del centro, así que nuestra recomendación es que os alojéis en zonas bien comunicadas en transporte público:</p>
        <ul>
            <li><strong>En metro</strong>: la estación Sierra de Guadalupe (L1) está a 10 minutos andando.</li>
            <li><strong>En tren</strong>: la estación Vallecas (C2 y C7) está a 10 minutos andando.</li>
            <li><strong>En autobús</strong>: hay varios autobuses que llegan: líneas 54, 58, 103, 142, 143, 63, 145.</li>
        </ul>
        <p>La línea 1 de metro comunica perfectamente el centro y la universidad. La zona de Méndez Álvaro y Pacífico están muy bien ubicadas y tendrán precios asequibles.</p>
        <p>Aparte, el campus tiene aparcamiento para quienes vengan en coche.</p>
        <p>La oferta de hoteles, hostales, o habitaciones privadas en Madrid es muy grande y hay un amplio abanico de opciones.</p>

        <ul>
            <li><a href="http://www.hotelmadridagumar.com" target="_blank">Hotel Agumar 4*</a> a medio camino de la estación Atocha de Metro (L1) y de la plaza de Mariano de Cavia (autobús 63). Sin desayuno 41€ aproximadamente la noche.</li>
            <li><a href="http://www.mediodiahotel.com/" target="_blank">Hotel Mediodía 2*</a> al lado de la estación Atocha de Metro (L1) y a unos 20 minutos andando para coger el autobús 63. Aproximadamente 46€ la noche.</li>
            <li><a href="http://www.nh-hotels.com/nh/en/hotels/spain/madrid/nh-pacifico.html" target="_blank">NH Pacífico 3*</a> al lado de la estación Puente de Vallecas de Metro (L1) y a 15 minutos andando de Conde de Casal. Entre 55€ y 60€ la noche.</li>
            <li><a href="http://www.ayrehoteles.com/" target="_blank" >Ayre Colón 4*</a> cerca del parque del Retiro, estación Sainz de Baranda de Metro (L6, transbordo cercano a L1) y a menos de 10 minutos andando de Conde de Casal. También 55€ la noche.</li>
            <li><a href="http://www.hotelclaridge.com/es/index" target="_blank">Claridge 4*</a> en la misma plaza Conde de Casal donde puedes coger los autobuses 63 y 145 directos a la universidad. Aproximadamente 75€ la noche.</li>
        </ul>

        <p>Estos son los hoteles que están bien comunicados con la universidad. El punto clave es la plaza Conde de Casal, de donde salen los autobuses 63 y 145.</p>

        <p>Si buscáis opciones especialmente asequibles, podéis buscar en redes como <a href="http://www.airbnb.com" target="_blank">www.airbnb.com</a> o albergues.</p>

        {% endblocktrans %}
    </div><!--accommodation-inside -->
</article>

pycones/web/templates/web/call4papers.html
{% load static from staticfiles %}
{% load i18n %}

<article class="call4papers" id="call4papers">
    <div class="call4papers-inside">
        <div class="call4papers-right">
            <img src="{% static 'web/img/people.png' %}" alt="PyConES Madrid 2013" border="0" align="right" />
            <div class="call4papers-btn">
                 <a href="mailto:call4papers2013@es.pycon.org">call4papers2013@es.pycon.org</a>
            </div>
        </div>
        <h2 class="white title">Call4papers</h2>
        {% blocktrans %}
        <p>¿Tienes una charla interesante sobre Python? ¡Anímate a compartirla con la comunidad!</p>
        <p>La conferencia consta de dos tracks: uno para principiantes y otro más avanzado. Esperamos charlas con Python como tema central: desarrollo, administración de sistemas, juegos, extensión con otros lenguajes, usos científicos, hardware (RaspberryPi), etc.</p>
        <p>El idioma de las charlas será el español o, en el caso de ponentes internacionales, el inglés. Durarán unos 50 minutos (aprox) y al final del día habrá una hora para charlas rápidas (5 minutos) que se organizarán en la propia conferencia.</p>
        <p>Envíanos tu propuesta antes del 15 de septiembre indicando el nivel de conocimientos requerido y un resumen del contenido para que podamos evaluarla.</p>
        <p>¡Esperamos vuestras propuestas!</p>
        {% endblocktrans %}
    </div><!-- call4papers-inside -->
</article>

pycones/web/templates/web/code_of_conduct.html
{% load static from staticfiles %}
{% load i18n %}

<aside id="text-code-of-conduct" class="text-more-info-footer">
    <div class="conduct-inside">
        <h2 class="title">{% trans 'Código de conducta' %}</h2>
        {% blocktrans %}
        <p>PyConES es una conferencia hecha por la comunidad pensada para la divulgación y colaboración dentro de la comunidad de desarrolladores.</p>

        <p>Valoramos la participación de cada miembro de la comunidad Python y queremos que todos los asistentes tengan una experiencia entretenida y satisfactoria. Para ello, se espera que todos los asistentes muestren respeto y cortesía hacia el resto durante la conferencia y todos los eventos relacionados con ella, estén oficialmente auspiciados por PyConES o no.</p>

        <p>En concreto, todos los delegados, conferenciantes, expositores y voluntarios que tomen parte en actividades relacionadas con PyConES deberán acatar el presente código de conducta. Los organizadores cuidarán del cumplimiento de este código durante el evento.</p>

        <p>PyConES aspira a crear un ambiente libre de acosos o discriminaciones por razón de género, orientación sexual, discapacidad, aspecto físico, etnia o religión. No se tolerará discriminación alguna bajo ninguna circunstancia.</p>

        <p>Todo el contenido de la conferencia deberá ajustarse a una audiencia profesional integrada por personas procedentes de sectores diferentes. Tanto el lenguaje como las imágenes sexualmente explícitos son inapropiados en la conferencia y en las charlas.</p>

        <p>Sé amable con los demás. No insultes o humilles a otros asistentes. Compórtate de manera profesional. Recuerda que las bromas sexistas, racistas o discriminatorias están prohibidas en la PyConES.</p>

        <p>Los asistentes que incumplan estas reglas podrán -a discreción de los organizadores- ser sancionados o expulsados de la conferencia sin derecho a reembolso.</p>

        <p>Se entiende por acoso todo comentario ofensivo alusivo al sexo, a preferencias sexuales, a discapacidades, al aspecto físico, a etnias o a religiones; toda pornografía en espacios públicos; toda intimidación deliberada, acecho o persecución; todo acoso mediante fotografías o grabaciones; toda interrupción constante de charlas u otras actividades; todo contacto físico inapropiado y toda propuesta sexual no deseada.</p>

        <p>Los participantes que sean apercibidos deberán desistir inmediatamente de su actitud.</p>

        <p>Los expositores, las casetas o pabellones de patrocinadores o empresas y actividades similares también están sujetas a la política antiacoso. En particular, los expositores no deberían utilizar material o llevar a cabo actividades sexistas. El personal de las casetas (incluyendo voluntarios) no deberían utilizar uniformes o vestimentas sexistas, puesto que se crearía un ambiente sexualizado.</p>

        <p>Cuida tu lenguaje. Recuerda que las bromas sexistas, racistas y excluyentes en general podrían ofender a otras personas. El lenguaje excesivamente soez y las bromas ofensivas son inapropiadas en PyConES.</p>

        <p>Si algún participante infringiera este código de conducta, la organización podrá tomar las medidas que considere adecuadas, como la amonestación o la expulsión sin derecho a rembolso.</p>

        <h3>Información de contacto</h3>

        <p>Si estás siendo objeto de acoso, notas que alguien está siendo acosado, o tienes cualquier otra preocupación, por favor ponte en contacto con un miembro del personal de la conferencia. El personal de la conferencia vestirá camisetas con la inscripción "Personal PyConES". Además puedes hablar con el personal del lugar y pedir que se te ponga en contacto con el responsable de la conferencia - Yamila Moreno</p>

        <p>Si se trata de una cuestión especialmente urgente, dirígete a cualquiera de estas personas:
        <ul>
            <li>Yamila  Moreno</li>
            <li>Alberto Chamorro</li>
            <li>Juan Luis Cano</li>
        </ul>
        </p>

        <p>El personal de la conferencia ayudará gustosamente a los participantes a que se pongan en contacto con el personal de seguridad del lugar o la policía local, y proporcionará escolta o socorrerá de cualquier otra forma a las víctimas de acoso para que puedan sentirse seguras durante el desarrollo de la conferencia. Tu bienestar es una de nuestras prioridades.</p>

        <p>Gracias por hacer de este un evento abierto a la comunidad y amistoso.</p>

        <h3>Licencia</h3>

        <p>Este Código de Conducta se basa en los códigos de conducta de PyCon US 2013 (<a href="https://us.pycon.org/2013/about/code-of-conduct" target="_new">https://us.pycon.org/2013/about/code-of-conduct/</a>) y PyConAr 2012 (<a href="http://ar.pycon.org/2012/conference/diversity" target="_new">http://ar.pycon.org/2012/conference/diversity/</a>), y está disponible bajo una licencia Creative Commons Atribución 3.0 España.</p>
        {% endblocktrans %}
        <a id="close-code-of-conduct" class="close-button">{% trans 'cerrar' %}</a>
    </div>
</aside>

pycones/web/templates/web/data.html
{% load static from staticfiles %}
{% load i18n %}
{% comment %}
<div class="nav-datos">
    <ul>
        <li id="current"><a href="#">{% trans 'Dónde/Cuándo' %}</a></li>
        <li><a href="#">{% trans 'Cómo llegar' %}</a></li>
        <li><a href="#">{% trans 'Conoce Madrid' %}</a></li>
        <li><a href="#">{% trans 'Alójate' %}</a></li>
    </ul>
</div><!-- nav-datos -->

<div class="informacion-slider">
    <div class="flexslider" id="informacion-slides">
        <ul class="slides">
            <li><!--Donde/Cuando--></li>
            <li><!--Como llegar--></li>
            <li><!--Conoce Madrid--></li>
            <li><!--Alojate--></li>
        </ul>
    </div>
</div>
{% endcomment %}
<div class="map-google">
            <div><p>Como no queremos que os perdáis, aquí tenéis un mapa detallado de la entrada. <a href="{% static 'web/img/location.png' %}"
                target="_blank">{% trans 'Ver aquí'%}</a></p></div>
            <iframe width="100%" height="450" frameborder="0" scrolling="no"
                marginheight="0" marginwidth="0"
                src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=UPM+Campus+Sur,+Madrid,+Espa%C3%B1a&amp;aq=0&amp;oq=upm+campus+su&amp;sll=37.0625,-95.677068&amp;sspn=81.556555,190.986328&amp;ie=UTF8&amp;hq=UPM+Campus+Sur,+Madrid,+Espa%C3%B1a&amp;t=m&amp;cid=1693672686789260872&amp;hnear=&amp;ll=40.396416,-3.630302&amp;spn=0.029415,0.257406&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
</div><!-- map-google -->

pycones/web/templates/web/end.html
{% load static from staticfiles %}
{% load i18n %}

<article class="tickets" id="end">
    <div class="tickets-inside">
        <h2 class="red title">{% trans 'Muchas gracias a todos :)' %}</h2>
        <p>{% trans 'Si te has perdido alguna charla, no desesperes: pondremos todos los vídeos a disposición pública próximamente.' %}</p>
    </div>
</article>

pycones/web/templates/web/footer.html
{% load static from staticfiles %}
{% load url from future %}
{% load i18n %}

 <footer id="contacto">
    <div class="footer-inside">
        <div class="footer-menu">
            <ul>
                <li><a class="logo-footer" href="#">PyCon 2013</a></li>
                {% comment %}
                <li><a href="#tickets"><span class="white">{ }</span> {% trans 'Entradas' %}</a></li>
                {% endcomment %}
                <li><a href="#informacion"><span class="white">{ }</span> {% trans 'Información' %}</a></li>
                <li><a href="#alojamiento"><span class="white">{ }</span> {% trans 'Alojamiento' %}</a></li>
                <li><a href="#patrocinadores"><span class="white">{ }</span> {% trans 'Patrocinadores' %}</a></li>
                <li><a href="#agenda"><span class="white">{ }</span> {% trans 'Agenda' %}</a></li>
                <li>&nbsp;</li>
                <li><a href="#" id="legal-terms" class="more-info-footer"><span class="red">{ }</span> {% trans 'Aviso legal' %}</a></li>
                <li><a href="#" id="code-of-conduct" class="more-info-footer"><span class="red">{ }</span> {% trans 'Código de conducta' %}</a></li>
            </ul>
        </div><!-- footer-menu -->
        <div class="footer-newsletter">
            <h2 class="white">Newsletter</h2>
            <form method="POST" action="{% url 'newsletter:subscribe_newsletter' %}" id="newsletter-form">
                {%csrf_token%}
                <span>{% trans 'Suscríbete!' %}</span>
                <input name="user_email" type="text" placeholder="{% trans 'Email' %}"/>
                <p id="newsletter-message"></p>
                <a href="#" id="subscribe-newsletter" class="button">{% trans 'Enviar' %}</a><br><br>
                <a href="{% url 'newsletter:latest_newsletter' %}" target="_blank" class="link-yellow">>>> {% trans 'Ver última newsletter' %}</a>
            </form>
        </div><!-- footer-newsletter -->
        <div class="footer-contacto">
            <h2 class="white">{% trans 'Contacta con nosotros' %}</h2>
            <p style="color: #ffffff">{% trans 'Escríbenos a' %} <a href="mailto:contacto2013@es.pycon.org">contacto2013@es.pycon.org</a> {% trans 'o rellena el siguiente formulario' %}</p>
            <form method="POST" id="contact-us-form" action="{% url 'contact_us' %}">
                {%csrf_token%}
                <span>{% trans 'Nombre' %}:</span>
                <input name="name" type="text" placeholder="{% trans 'Nombre' %}"/>
                <span>{% trans 'Email' %}:</span>
                <input name="contact_email" type="text" placeholder="{% trans 'Email' %}"/>
                <span>{% trans 'Mensaje' %}:</span>
                <textarea name="message"></textarea>
                <p id="contact-us-message"></p>
                <a href="#" id="contact-us" class="button">{% trans 'Enviar' %}</a>
            </form>
        </div><!-- footer-contacto -->
        {% comment %}<div id="footer-copy">Copyright © 1990-2013, Python Software Foundation</div>{% endcomment %}
    </div><!-- footer-inside -->
</footer>

pycones/web/templates/web/home.html
{% load static from staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% trans 'PyCon España 2013' %}</title>
        <meta name="description" content="Comunidad Internacional de Python">
        <meta name="viewport" content="width=device-width">
        <!-- Google fonts -->
        <link rel="icon" href="{% static 'web/img/favicon.ico'%}" type="image/x-icon">
        <link rel="shortcut icon" href="{% static 'web/img/favicon.ico'%}" type="image/x-icon">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <!-- Flexslider -->
        <link rel="stylesheet" href="{% static 'web/css/flexslider.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    </head>
    <body>
        {% include 'web/header.html' %}
        {% include 'web/language_selector.html' %}
        {% include 'web/end.html' %}
        {% include 'web/info.html' %}
        {% include 'web/skyline.html' %}
        {% include 'web/data.html' %}
        {% include 'web/accommodation.html' %}
        {% include 'web/sponsors.html' %}
        <div class="imagen-landscape1">
            <div class="imagen-landscape-inside">
                <div class="imagen-pie">
                    <p>PyCon Santa Clara 2013</p>
                    <p><a href="http://www.flickr.com/photos/jaaaarel/" target="_blank">{% trans 'Foto: Jaaaarel' %}</a></p>
                </div>
            </div>
        </div><!-- imagen-landscape1 -->
        {% include 'web/schedule.html' %}
        <div class="imagen-landscape2">
            <div class="imagen-landscape2-inside">
                <div class="imagen-pie">
                    <p>PyCon Santa Clara 2013</p>
                    <p><a href="http://www.flickr.com/photos/jaaaarel/" target="_blank">{% trans 'Foto: Jaaaarel' %}</a></p>
                </div>
            </div>
        </div><!-- imagen-landscape2 -->

        {% include 'web/code_of_conduct.html' %}
        {% include 'web/legal_terms.html' %}
        {% include 'web/footer.html' %}
    </body>

    <script src="{% static 'web/js/jquery-1.8.3.min.js' %}"></script>
    <script src="{% static 'web/js/jquery.flexslider.js' %}"></script>
    <script src="{% static 'web/js/web.js' %}"></script>

    <script>
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-5340683-11']);
    _gaq.push(['_trackPageview']);
    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
</html>

pycones/web/templates/web/language_selector.html
{% load static from staticfiles %}
{% load i18n %}

<article class="language-selector">
    <div class="language-selector-inside">
        <ul class="languages">
            <form id="setLang" name="setLang" action="/i18n/setlang/" method="POST">{% csrf_token %}
                <input type="hidden" name="language" id="language">

                <li>
                    <a href="#" data-lang="es">Español</a>
                </li>
                <li>
                    <a href="#" data-lang="ca">Català</a>
                </li>
                <li>
                    <a href="#" data-lang="ga">Galego</a>
                </li>
                <li>
                    <a href="#" data-lang="eu">Euskara</a>
                </li>
                <li>
                    <a href="#" data-lang="en">English</a>
                </li>

            </form>
        </ul>
    </div><!-- informacion-inside -->
</article>

pycones/web/templates/web/skyline.html
{% load static from staticfiles %}
{% load i18n %}

<article class="datos">
    <div class="datos-inside">
        <div class="datos-text">
            <h1 class="red">{% trans 'Madrid, 23-24 de noviembre de 2013' %}</h1>
            <p class="red">{% trans 'EU Informática, Universidad Politécnica de Madrid' %}</p>
        </div>
    </div><!-- datos-inside -->
</article>

pycones/web/templates/web/talk.html
                <span class="paper-title">{{talk.title}}</span>
                <div>
                    <p>{{talk.abstract}}</p>
                    {% for speaker in talk.speakers.all %}
                    <a target="_blank" href="http://twitter.com/{{speaker.twitter}}">{{speaker.name}}</a>
                    <p>{{speaker.bio}}</p>
                    {% endfor %}
                </div>

pycones/web/templates/web/tickets.html
{% load static from staticfiles %}
{% load i18n %}

<article class="tickets" id="tickets">
    <div class="tickets-inside">
        <h2 class="red title">{% trans 'Entradas' %}</h2>
        <p>{% trans 'Agotadas las entradas. ¡Nos vemos en noviembre!' %}</p>
        <p>{% trans 'Si no has conseguido tu entrada, no desesperes, grabaremos todas las charlas y las pondremos a disposición pública tras el evento.' %}
    </div>
</article>